version: '3'

services:
  db:
    image: postgres
    container_name: db
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - djangonetwork
    env_file:
      - .env

  web:
    build: .
    command: bash -c 'python source/manage.py migrate && python source/manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
    env_file:
      - .env

networks:
  djangonetwork:
    driver: bridge

volumes:
  postgres_data: