# Generated by Django 4.2.11 on 2024-03-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_order_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_id',
        ),
    ]
